# Generated by Django 5.1.2 on 2024-10-20 16:28

import django.contrib.auth.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.user_picture_file_path
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user-5f853a4d-8f00-11ef-bc46-f020ff234df7",
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
